### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by glorialee820**

### CODE REVIEW

**Review by lfeldman — CHANGES_REQUESTED** [review]
It looks like there is a duplication of the entries in `datasources.tf `and `data.tf` files. I am not able to pass terraform init command:

image

**Review by lfeldman — CHANGES_REQUESTED** [review]
It looks like the removal of `datasources.tf` has caused another problem:
image
Please re-add this datasource to `data.tf` file.

**Review by lfeldman — CHANGES_REQUESTED** [review]
@glorialee820 - now I see this issue:
image

**Comment by glorialee820** [comment]
The GPU image seems to only support GPU3.x and up since GPU2.x is deprecated, I will try and get you a guest user in my tenancy where GPUs are available.

**Review by lfeldman — CHANGES_REQUESTED** [review]
In your tenancy, I have tested BM shape, but it still errors out:
image

How `terraform.tfvars` file should be populated to mitigate this error. My setup is as follows:
```
(...)
use_marketplace_image = false
use_standard_image = true
(...)
```

**Review by lfeldman — COMMENTED** [review]
@glorialee820 I have changed `cluster_network=true` value. Now it works: 
image

I will add my commit with updated README file (section for `terraform.tfvars` file)

**Review by lfeldman — COMMENTED** [review]
I will now test it in ORM/RMS.

**Review by lfeldman — CHANGES_REQUESTED** [review]
@glorialee820 I have tested the stack with ORM/RMS, but it errors out as follows:
image

Please propose the changes to fix it.

**Review by lfeldman — APPROVED** [review]
I have repeated it a second time and now it is OK. Looks like a one-time issue. 
image

**Pull request merged**
